### ISSUE TITLE
Missing spyder_kernels dependency after update to version 5

### ISSUE THREAD

**Issue by kmilos** [conda-forge/spyder-feedstock#104] opened 2021-04-05 18:36 UTC
This is on Windows after today's update to version 5:

![image](https://user-images.githubusercontent.com/4973094/113611026-37a35a80-964e-11eb-99b5-032ed5c7c0de.png)

Tried resetting spyder settings, result is the same...

```
> conda list spyder
# packages in environment at C:\Miniconda3\envs\dev:
#
# Name                    Version                   Build  Channel
pyls-spyder               0.3.2              pyhd8ed1ab_0    conda-forge
spyder                    5.0.0            py37h03978a9_0    conda-forge
spyder-kernels            2.0.1            py37h03978a9_0    conda-forge
```

**Comment by ccordoba12** [comment] 2021-04-05 21:19
Duplicate of spyder-ide/spyder#15091. It'll be fixed in our next version (5.0.1).

**Closed by ccordoba12** 2021-04-05 21:19 UTC
